### ISSUE TITLE
Add Multi-Architecture (ARM64) Support for Docker Image

### ISSUE THREAD

**Issue by cillin89** [dreeveapp/dreeve#12]
Any plans for this?

**Comment by robiningelbrecht** [comment]
Would need to look into this, but shouldn't be too hard

**Comment by FoxxMD** [comment]
This can be done by modifying [`docker-image.yml`](https://github.com/robiningelbrecht/strava-statistics/blob/master/.github/workflows/docker-image.yml):

Add these steps before the `build-push-action` step

```yaml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
```

Add this line to the `with` properties of `build-push-action` step

```yaml
platforms: linux/amd64,linux/arm64
```
