### ISSUE TITLE
Can only see Rides

### ISSUE THREAD

**Issue by psyciknz** [dreeveapp/dreeve#128]
**Describe the bug**

**Tell us which app version you are on**
`v0.3.1` I see 0.3.2 is out, but having just pulled it didn't pick that up.

**To Reproduce**
Navigate to Dashboard or All Activities

**Expected behavior**
That All Activities would show all activities.  And then if I choose to filter to just bike or run then that occurs.
Currently filters to bike only, and cannot change to run.

**Provide your docker compose config**
```
strava:
    image: robiningelbrecht/strava-statistics:latest
    container_name: strava
    volumes:
      - ${BASEPATH}/ryot/strava:/config
      - strava_build:/var/www/build
      - strava_storage:/var/www/storage
    env_file: .env
    environment:
      - PGID=998
      - PUID=1000
      - DATABASE_URL=$DATABASE_URL
      - UNIT_SYSTEM=metric
      - STRAVA_CLIENT_ID=$STRAVA_CLIENT_ID
      - STRAVA_CLIENT_SECRET=$STRAVA_CLIENT_SECRET
      - STRAVA_REFRESH_TOKEN=$STRAVA_REFRESH_TOKEN
      - ATHLETE_BIRTHDAY=$ATHLETE_BIRTHDAY
      - ATHLETE_WEIGHTS=$ATHLETE_WEIGHTS
      - FTP_VALUES=$FTP_VALUES

    labels:
      - autoheal=true
      - com.centurylinklabs.watchtower.enable=true
      - caddy=*.$INTDOMAIN
      - caddy.@strava=host strava.$INTDOMAIN
      - caddy.route.1_reverse_proxy=@strava "{{ upstreams 8080 }}"
      - homepage.group=Media
      - homepage.name=Strava
      #https://github.com/walkxcode/dashboard-icons
      - homepage.icon=strava.png
      - homepage.href=https://strava.$INTDOMAIN
      - homepage.description=Strava Statistics ($HOSTNAME)
      - deck-chores.strava-sync.command=bash -c "/config/runupdate.sh"
      - deck-chores.strava-sync.cron=* * * 8 45 0
    ports:
      - 8094:8080
    networks:
      - ryot
      - caddy-proxy
```

.env
```
DATABASE_URL="sqlite:///%kernel.project_dir%/storage/database/strava.db?charset=utf8mb4"

# The client id of your Strava app.
STRAVA_CLIENT_ID=REDACTED
# The client secret of your Strava app.
STRAVA_CLIENT_SECRET=REDACTED
# The refresh of your Strava app.
STRAVA_REFRESH_TOKEN=REDACTED

# Allowed options: metric or imperial
UNIT_SYSTEM=metric
# Activity types to import. Allowed options: "Ride", "VirtualRide" and "Run"
ACTIVITY_TYPES_TO_IMPORT='["Ride", "Run"]'
# Your birthday. Needed to calculate heart rate zones.
ATHLETE_BIRTHDAY=REDACTED
# History of weight (in kg or pounds, depending on UNIT_SYSTEM). Needed to calculate relative w/kg.
ATHLETE_WEIGHTS='{
    "2024-12-31": 74.6,
    "2024-01-01": 70.3
}'
# History of FTP. Needed to calculate activity stress level
FTP_VALUES='{
    "2024-12-31": 198,
    "2024-01-01": 220
}'
```

* be sure to redact sensitive information
* include docker-compose.yml
* include .env

**Screenshots**
![image](https://github.com/user-attachments/assets/37a0dd51-357e-4865-8050-3167cb027c05)
![image](https://github.com/user-attachments/assets/ad111d27-979b-42dc-8080-8cf25b9bc993)
