### ISSUE TITLE
Eddington graph is empty with JS error since v0.4.X

### ISSUE THREAD

**Issue by llaumgui** [dreeveapp/dreeve#187]
**Describe the bug**
Since v0.4.x, the Eddington graph is empty with JS issue:

```javascript
Uncaught TypeError: t.targetEl is null
```

**Tell us which app version you are on**
`v0.4.1`

**To Reproduce**

* Make a import.
* Make a build.
* Go to Eddington page.

**Expected behavior**
Eddington working ;-).

**Provide your docker compose config**
The strava statistics info on my portainer

```yaml
## strava_statistics
  strava_statistics:
    container_name: strava_statistics
    hostname: strava-statistics
    image: robiningelbrecht/strava-statistics:latest
    restart: "unless-stopped"
    env_file: stack.env
    environment:
      LOCALE: 'fr_FR'
      STRAVA_CLIENT_ID: ''
      STRAVA_CLIENT_SECRET: ''
      STRAVA_REFRESH_TOKEN: ''
      NUMBER_OF_NEW_ACTIVITIES_TO_PROCESS_PER_IMPORT: '250'
      UNIT_SYSTEM: 'metric'
      TIME_FORMAT: '24'
      DATE_FORMAT: 'DAY-MONTH-YEAR'
      SPORT_TYPES_TO_IMPORT: '[]'
      ATHLETE_BIRTHDAY: ''
      ATHLETE_WEIGHTS: ''
      FTP_VALUES: ''
      NTFY_URL: ''
    labels:
      - traefik.enable=true
      - traefik.http.routers.strava_statistics.entrypoints=web
      - traefik.http.routers.strava_statistics.rule=Host("strava.xxxx.fr")
      - traefik.http.routers.strava_statistics.tls.certresolver=letsencrypt
      - traefik.http.routers.strava_statistics.middlewares=compress@file,authelia@file,headers_hsts@file
    volumes:
      - /srv/dev-disk-by-label-omvdata/strava/build:/var/www/build:rw
      - /srv/dev-disk-by-label-omvdata/strava/database:/var/www/storage/database:rw
      - /srv/dev-disk-by-label-omvdata/strava/files:/var/www/storage/files:rw
    networks:
      - frontend
    expose:
      - 8080
```

**Screenshots**

![Image](https://github.com/user-attachments/assets/0f3fac20-911e-466e-b788-91f9081106db)
