### ISSUE TITLE
Container cant access "unix:/tmp/php-fpm.sock"  and "/var/www/build/html/error/50x.html"

### ISSUE THREAD

**Issue by sternensim** [dreeveapp/dreeve#268]
**Describe the bug**
There is no data in ./build:/var/www/build 
Also the container is not able to reach the necessary php files. see below

**To Reproduce**
I run the Container like described in the readme.md 

**Expected behavior**
The container starts, puts data in ./build:/var/www/build  and shows a webUI

**Provide your docker compose config**

```yml
services:
  app:
    image: robiningelbrecht/strava-statistics:latest
    volumes:
      - /home/simon/strava/simon/build:/var/www/build
      - /home/simon/strava/simon/storage/database:/var/www/storage/database
      - /home/simon/strava/simon/storage/files:/var/www/storage/files
    environment:
      MANIFEST_APP_URL: "http://192.168.2.104:8099/"
      STRAVA_CLIENT_ID: "###"
      STRAVA_CLIENT_SECRET: "###"
      STRAVA_REFRESH_TOKEN: "###"
      NUMBER_OF_NEW_ACTIVITIES_TO_PROCESS_PER_IMPORT: "250"
      IMPORT_AND_BUILD_SCHEDULE: "5 4 * * *"
      TZ: "Etc/de"
      LOCALE: "en_US"
      UNIT_SYSTEM: "metric"
      TIME_FORMAT: "24"
      DATE_FORMAT: "DAY-MONTH-YEAR"
      SPORT_TYPES_TO_IMPORT: "[]"
      ATHLETE_BIRTHDAY: "2000-06-05"
      ATHLETE_WEIGHTS: '{"2025-01-01": 110}'
      FTP_VALUES: "{}"
      NTFY_URL: ""
      ACTIVITIES_TO_SKIP_DURING_IMPORT: "[]"
      #PUID: "0"
      #PGID: "0"

    ports:
      - 8099:8099
````
     
**Environment configuration**

root@f9fb01009502:/var/www# php bin/console app:debug:environment

```
Strava Statistics
=================

 Please copy all this output into the description of the bug ticket


 [WARNING] Do not forget to redact sensitive information


+------------------------------------------------+--------------------------------------------------------------------------+
| ENV variable                                   | Value                                                                    |
+------------------------------------------------+--------------------------------------------------------------------------+
| APP_VERSION                                  | v0.4.12                                                                  |
| FTP_VALUES                                     | {}                                                                       |
| S6_STAGE2_HOOK                           | /docker-mods                                                             |
| HOSTNAME                                     | f9fb01009502                                                             |
| PHP_INI_DIR                                    | /etc/php84                                                               |
| SHLVL                                              | 1                                                                        |
| HOME                                              | /root                                                                    |
| OLDPWD                                         | /var/www/build                                                           |
| NUMBER_OF_NEW_ACTIVITIES_TO_PROCESS_PER_IMPORT | 250                                                                      |
| STRAVA_REFRESH_TOKEN                           | ####                                 |
| ATHLETE_WEIGHTS                                | {"2025-01-01": 110}                                                      |
| S6_VERBOSITY                                   | 1                                                                        |
| PS1                                            | $(whoami)@$(hostname):$(pwd)\$                                           |
| LOCALE                                         | en_US                                                                    |
| PGID                                           | 100                                                                      |
| TIME_FORMAT                                    | 24                                                                       |
| DATE_FORMAT                                    | DAY-MONTH-YEAR                                                           |
| IMPORT_AND_BUILD_SCHEDULE                      | 5 4 * * *                                                                |
| S6_CMD_WAIT_FOR_SERVICES_MAXTIME               | 0                                                                        |
| TERM                                           | xterm                                                                    |
| PATH                                           | /lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin |
| SPORT_TYPES_TO_IMPORT                          | []                                                                       |
| PUID                                           | 65534                                                                    |
| ATHLETE_BIRTHDAY                               | 2000-06-05                                                               |
| MANIFEST_APP_URL                               | http://192.168.2.104:8099/                                               |
| VIRTUAL_ENV                                    | /lsiopy                                                                  |
| PWD                                            | /var/www                                                                 |
| ACTIVITIES_TO_SKIP_DURING_IMPORT               | []                                                                       |
| NTFY_URL                                       |                                                                          |
| TZ                                             | Etc/de                                                                   |
| STRAVA_CLIENT_ID                               | ####|
| STRAVA_CLIENT_SECRET                           | #####|
| UNIT_SYSTEM                                    | metric                                                                   |
| LINES                                          | 57                                                                       |
| COLUMNS                                        | 206                                                                      |
| SHELL_VERBOSITY                                | 0                                                                        |
+------------------------------------------------+--------------------------------------------------------------------------+



GID/UID

───────────────────────────────────────

User UID:    65534

User GID:    100

───────────────────────────────────────

[custom-init] No custom files found, skipping...

[10-Feb-2025 22:07:50] NOTICE: fpm is running, pid 150

[10-Feb-2025 22:07:50] NOTICE: ready to handle connections

2025/02/10 22:08:16 [crit] 163#163: *1 connect() to unix:/tmp/php-fpm.sock failed (13: Permission denied) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /fpm-ping HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "127.0.0.1:8080"

2025/02/10 22:08:16 [error] 163#163: *1 open() "/var/www/build/html/error/50x.html" failed (2: No such file or directory), client: 127.0.0.1, server: _, request: "GET /fpm-ping HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock", host: "127.0.0.1:8080"

127.0.0.1 - - [10/Feb/2025:22:08:16 +0000] "GET /fpm-ping HTTP/1.1" 404 146 "-" "curl/8.12.0" "-" 0.000 0.000 . -
```
