### ISSUE TITLE
Cannot get it to run

### ISSUE THREAD

**Issue by vordenken** [dreeveapp/dreeve#32]
Hi @robiningelbrecht ,
thanks for this cool project :)
I tried using it but just get 
"no configuration file provided: not found"
after running
"docker compose exec app bin/console app:strava:import-data".

I find the instructions a bit confusing... what am I doing wrong?

**Comment by robiningelbrecht** [comment]
@vordenken can you post your docker-compose.yml en .env file please?

**Comment by vordenken** [comment]
Yeah sure :)
I edited it a bit because I'm trying to run it with portainer (stacks). The other variables like the IDs are substituted by portainer.
I tinkered a bit more with it and got it running now, but I had to chmod 777 the folders, otherwise the database cannot be created. Never had that issue before.
Also instead of running the docker compose exec command I had to use the portainer "connect to Container console" feature and use "bin/console app:strava:import-data" as a custom command.

Are there any plans to do the import/building via the webui? Because in my setup I cannot automate the import with the current way.

```
---
services:

  app:
    image: robiningelbrecht/strava-statistics:latest
    volumes:
      - /mnt/docker/strava-statistics/build:/var/www/build
      - /mnt/docker/strava-statistics/database:/var/www/storage/database
      - /mnt/docker/strava-statistics/files:/var/www/storage/files
    environment:
      - DATABASE_URL=$DATABASE_URL
      - UNIT_SYSTEM=metric
      - STRAVA_CLIENT_ID=$STRAVA_CLIENT_ID
      - STRAVA_CLIENT_SECRET=$STRAVA_CLIENT_SECRET
      - STRAVA_REFRESH_TOKEN=$STRAVA_REFRESH_TOKEN
      - ATHLETE_BIRTHDAY=$ATHLETE_BIRTHDAY
      - ATHLETE_WEIGHTS=$ATHLETE_WEIGHTS
      - FTP_VALUES=$FTP_VALUES
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strava.rule=Host(`strava-statistics.MYURL.TLD`)"
      - "traefik.http.routers.strava.entrypoints=websecure"
      - "traefik.http.routers.strava.tls.certresolver=myresolver"
      - "traefik.http.services.strava.loadbalancer.server.port=8080"
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true
```
