### ISSUE TITLE
No Configuration File Provided

### ISSUE THREAD

**Issue by isaacrlevin** [dreeveapp/dreeve#332]
No matter what I have tried, I am unable to get the container to read my configuration file. Here is my docker compose file. I have chmod 777 on the file

```yml
services:
  strava:
    container_name: strava
    image: robiningelbrecht/strava-statistics:latest
    volumes:
      - /mnt/data/appdata/strava/build:/var/www/build
      - /mnt/data/appdata/strava/storage/database:/var/www/storage/database
      - /mnt/data/appdata/strava/storage/files:/var/www/storage/files
    env_file: ./.env
    ports:
      - 8087:8080
```

Is there a place in the container I should look to see where it should be?
