### ISSUE TITLE
Import crashes out at specific activity

### ISSUE THREAD

**Issue by Jleagle** [dreeveapp/dreeve#505]
**Describe the bug**

My import goes until it gets to a specific activity (https://www.strava.com/activities/11126767554), which looks like this in Strava:

<img width="848" alt="Image" src="https://github.com/user-attachments/assets/bd13ed02-859b-4600-be22-1599b0256234" />

Once it tries to import this activity it gets a 500 and stops importing activities and moves onto activity streams. So i've never imported anything older than this.

```
  => Updated activity "Morning Run - 31-01-2024"
  => Updated activity "Morning Walk - 30-01-2024"
  => Updated activity "Afternoon Walk - 28-01-2024"
  => Updated activity "Morning Walk - 27-01-2024"
  => Updated activity "Afternoon Walk - 26-01-2024"
  => Updated activity "Morning Walk - 25-01-2024"
Strava API threw error: Server error: `GET https://www.strava.com/api/v3/activities/11126767554` resulted in a `500 Internal Server Error` response:
{"message":"error"}

Importing activity splits...
  => Added 7 new activity splits for 1 activities
Importing activity streams...
  => Imported activity stream "14200455793 - moving"
  => Imported activity stream "14200455793 - latlng"
```

**To Reproduce**
`docker compose exec strava bin/console app:strava:import-data`

**Expected behavior**
If it can't fetch an activity for some reason, could it try to keep going depending on the error.

**Provide your docker compose config**

```
  strava:
    image: "robiningelbrecht/strava-statistics:latest"
    container_name: "strava"
    hostname: "strava"
    restart: "unless-stopped"
    volumes:
      - "${HOME}/Strava/build:/var/www/build"
      - "${HOME}/Strava/database:/var/www/storage/database"
      - "${HOME}/Strava/files:/var/www/storage/files"
    ports:
      - "8082:8080"
    environment:
      - "MANIFEST_APP_URL=https://strava.---.com/"
      - "STRAVA_CLIENT_ID=---"
      - "STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET}"
      - "STRAVA_REFRESH_TOKEN=${STRAVA_REFRESH_TOKEN}"
      - "NUMBER_OF_NEW_ACTIVITIES_TO_PROCESS_PER_IMPORT=250"
      - "IMPORT_AND_BUILD_SCHEDULE='0 4 * * *'"
      - "TZ=Europe/London"
      - "LOCALE=en_US"
      - "UNIT_SYSTEM=metric"
      - "TIME_FORMAT=24"
      - "DATE_FORMAT=DAY-MONTH-YEAR"
      - "SPORT_TYPES_TO_IMPORT=[]"
      - "ATHLETE_BIRTHDAY=1987-10-02"
      - "ATHLETE_WEIGHTS=[]"
      - "FTP_VALUES=[]"
      - "PROFILE_PICTURE_URL="
      - "ZWIFT_LEVEL="
      - "ZWIFT_RACING_SCORE="
      - "NTFY_URL="
      - "ACTIVITIES_TO_SKIP_DURING_IMPORT=[]"
```

**Environment configuration**

```
+------------------------------------------------+--------------------------------------------------------------------------+
| ENV variable                                   | Value                                                                    |
+------------------------------------------------+--------------------------------------------------------------------------+
| APP_VERSION                                    | v1.1.2                                                                   |
| PATH                                           | /lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin |
| HOSTNAME                                       | strava                                                                   |
| TERM                                           | xterm                                                                    |
| PROFILE_PICTURE_URL                            |                                                                          |
| ATHLETE_WEIGHTS                                | []                                                                       |
| NUMBER_OF_NEW_ACTIVITIES_TO_PROCESS_PER_IMPORT | 250                                                                      |
| SPORT_TYPES_TO_IMPORT                          | []                                                                       |
| ATHLETE_BIRTHDAY                               | ----------                                                               |
| STRAVA_CLIENT_SECRET                           | --- -------------------------------------                                |
| MANIFEST_APP_URL                               | https://strava.--------.com/                                             |
| NTFY_URL                                       |                                                                          |
| STRAVA_REFRESH_TOKEN                           | ----------------------------------------                                 |
| DATE_FORMAT                                    | DAY-MONTH-YEAR                                                           |
| STRAVA_CLIENT_ID                               | ------                                                                   |
| TIME_FORMAT                                    | 24                                                                       |
| ZWIFT_LEVEL                                    |                                                                          |
| TZ                                             | Europe/London                                                            |
| ACTIVITIES_TO_SKIP_DURING_IMPORT               | []                                                                       |
| IMPORT_AND_BUILD_SCHEDULE                      | '0 4 * * *'                                                              |
| LOCALE                                         | en_US                                                                    |
| ZWIFT_RACING_SCORE                             |                                                                          |
| UNIT_SYSTEM                                    | metric                                                                   |
| FTP_VALUES                                     | []                                                                       |
| PS1                                            | $(whoami)@$(hostname):$(pwd)\$                                           |
| HOME                                           | /root                                                                    |
| S6_CMD_WAIT_FOR_SERVICES_MAXTIME               | 0                                                                        |
| S6_VERBOSITY                                   | 1                                                                        |
| S6_STAGE2_HOOK                                 | /docker-mods                                                             |
| VIRTUAL_ENV                                    | /lsiopy                                                                  |
| PHP_INI_DIR                                    | /etc/php84                                                               |
| PUID                                           | 65534                                                                    |
| PGID                                           | 100                                                                      |
| LINES                                          | 79                                                                       |
| COLUMNS                                        | 362                                                                      |
| SHELL_VERBOSITY                                | 0                                                                        |
+------------------------------------------------+--------------------------------------------------------------------------+ 
```

**Screenshots**
<img width="1064" alt="Image" src="https://github.com/user-attachments/assets/346c7eca-81ba-458a-9724-fd072f7620ad" />
