### ISSUE TITLE
Cant change to &scope=activity:read_all

### ISSUE THREAD

**Issue by lagge78** [dreeveapp/dreeve#514]
Hello,
I trying to get this docker up and running but I have som issues with the Strava setup.

I have followed 11step instruction. I got the authorization code. put it into postman and got a response with a refresh token. I went into the Swagger UI and pressed authorize and get the list of possible scopes. When I press the check mark for activity:read_all and press authorize I end up at a page stating:

_**{"message":"Bad Request","errors":[{"resource":"Application","field":"redirect_uri","code":"invalid"}]}**_

And the refresh token under my API application on Strava still states scope: read.

I have tried several times but I seem not to be able to change the scope. Any idea what can be wrong?
The way I setup the application?

![Image](https://github.com/user-attachments/assets/1a3c0d92-b587-4423-9bc5-82d03b421ce6)

**Comment by robiningelbrecht** [comment]
Hi @lagge78 ,

To my knowledge the docs don't state "Swagger UI".
After step 11 you will get a refresh token:

```yml
{
    "token_type": "Bearer",
    "expires_at": 1562908002,
    "expires_in": 21600,
    "refresh_token": "REFRESHTOKEN",
    "access_token": "ACCESSTOKEN",
    "athlete": {
        "id": 123456,
        "username": "MeowTheCat",
        "resource_state": 2,
        "firstname": "Meow",
        "lastname": "TheCat",
        "city": "",
        "state": "",
        "country": null,
        ...
    }
}
```

You need to copy/paste that token to be able to use this app.
