### ISSUE TITLE
All Activities Page Stuck on 'Loading data...' in Web UI

### ISSUE THREAD

**Issue by juanra** [dreeveapp/dreeve#522]
**Describe the bug**
The "All activities" section in the Statistics for Strava web interface remains stuck at "Loading data..." and never loads the list of activities. This issue persists even after refreshing the page or restarting the container.

**To Reproduce**
1. Start the Statistics for Strava service using Docker Compose.
2. Navigate to the web interface.
3. Click on "All activities" in the sidebar.
4. Observe that the data does not load and remains stuck on "Loading data..."

**Expected behavior**
The activity list should load normally and display the filtered results (129 in this case).

**Provide your docker compose config**

```yaml
services:
  strava-stats:
    environment:
      - MANIFEST_APP_URL=http://your-domain.com/
      - STRAVA_CLIENT_ID=your_strava_client_id
      - STRAVA_CLIENT_SECRET=your_strava_client_secret
      - STRAVA_REFRESH_TOKEN=your_strava_refresh_token
      - NUMBER_OF_NEW_ACTIVITIES_TO_PROCESS_PER_IMPORT=250
      - IMPORT_AND_BUILD_SCHEDULE=5 4 * * *
      - TZ=America/Your_Timezone
      - LOCALE=en_US
      - UNIT_SYSTEM=metric
      - TIME_FORMAT=12
      - DATE_FORMAT=DAY-MONTH-YEAR
      - SPORT_TYPES_TO_IMPORT=[]
      - ACTIVITY_VISIBILITIES_TO_IMPORT=[]
      - SKIP_ACTIVITIES_RECORDED_BEFORE=
      - ACTIVITIES_TO_SKIP_DURING_IMPORT=[]
      - ATHLETE_BIRTHDAY=yyyy-mm-dd
      - ATHLETE_WEIGHT_HISTORY={"2024-10-27":90.6,"2024-10-28":90.5,...,"2025-04-15":84.2}
      - MAX_HEART_RATE_FORMULA=fox
      - FTP_HISTORY=[]
      - PROFILE_PICTURE_URL=https://your-cloudfront-url.com/profile.jpg
      - ZWIFT_LEVEL=
      - ZWIFT_RACING_SCORE=
      - NTFY_URL=
      - PUID=your_puid
      - PGID=your_pgid
    image: robiningelbrecht/strava-statistics:latest
    ports:
      - '8080:8080'
    volumes:
      - /path/to/your/data/build:/var/www/build
      - /path/to/your/data/database:/var/www/storage/database
      - /path/to/your/data/files:/var/www/storage/files
      - /path/to/your/data/gear-maintenance:/var/www/storage/gear-maintenance
```

**Environment configuration**

```sh
+------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ENV variable                                   | Value                                                                                                                                                                       |
+------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| APP_VERSION                                    | v1.2.4                                                                                                                                                                      |
| ZWIFT_RACING_SCORE                             |                                                                                                                                                                             |
| S6_STAGE2_HOOK                                 | /docker-mods                                                                                                                                                                |
| HOSTNAME                                       | anonymized-hostname                                                                                                                                                         |
| PHP_INI_DIR                                    | /etc/php84                                                                                                                                                                  |
| SHLVL                                          | 1                                                                                                                                                                           |
| HOME                                           | /root                                                                                                                                                                       |
| NUMBER_OF_NEW_ACTIVITIES_TO_PROCESS_PER_IMPORT | 250                                                                                                                                                                         |
| STRAVA_REFRESH_TOKEN                           | REDACTED_REFRESH_TOKEN                                                                                                                                                      |
| S6_VERBOSITY                                   | 1                                                                                                                                                                           |
| PS1                                            | $(whoami)@$(hostname):$(pwd)\$                                                                                                                                              |
| LOCALE                                         | en_US                                                                                                                                                                       |
| PGID                                           | anonymized_pg_id                                                                                                                                                            |
| PROFILE_PICTURE_URL                            | https://your-cloudfront-url.com/path/to/profile.jpg                                                                                                                         |
| ZWIFT_LEVEL                                    |                                                                                                                                                                             |
| DATE_FORMAT                                    | DAY-MONTH-YEAR                                                                                                                                                              |
| IMPORT_AND_BUILD_SCHEDULE                      | 5 4 * * *                                                                                                                                                                   |
| TIME_FORMAT                                    | 12                                                                                                                                                                          |
| S6_CMD_WAIT_FOR_SERVICES_MAXTIME               | 0                                                                                                                                                                           |
| TERM                                           | xterm                                                                                                                                                                       |
| PATH                                           | /lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin                                                                                                    |
| FTP_HISTORY                                    | []                                                                                                                                                                          |
| SPORT_TYPES_TO_IMPORT                          | []                                                                                                                                                                          |
| ACTIVITY_VISIBILITIES_TO_IMPORT                | []                                                                                                                                                                          |
| PUID                                           | anonymized_pu_id                                                                                                                                                            |
| MAX_HEART_RATE_FORMULA                         | fox                                                                                                                                                                         |
| ATHLETE_BIRTHDAY                               | REDACTED_BIRTHDATE                                                                                                                                                          |
| MANIFEST_APP_URL                               | http://your-domain.com/                                                                                                                                                     |
| VIRTUAL_ENV                                    | /lsiopy                                                                                                                                                                     |
| PWD                                            | /var/www                                                                                                                                                                    |
| SKIP_ACTIVITIES_RECORDED_BEFORE                |                                                                                                                                                                             |
| ACTIVITIES_TO_SKIP_DURING_IMPORT               | []                                                                                                                                                                          |
| NTFY_URL                                       |                                                                                                                                                                             |
| TZ                                             | America/Your_Timezone                                                                                                                                                       |
| STRAVA_CLIENT_ID                               | REDACTED_CLIENT_ID                                                                                                                                                          |
| STRAVA_CLIENT_SECRET                           | REDACTED_CLIENT_SECRET                                                                                                                                                      |
| UNIT_SYSTEM                                    | metric                                                                                                                                                                      |
| ATHLETE_WEIGHT_HISTORY                         | {"2024-10-27":90.6, "2024-10-28":90.5, ..., "2025-04-15":84.2}                                                                                                               |
| LINES                                          | 55                                                                                                                                                                          |
| COLUMNS                                        | 199                                                                                                                                                                         |
| SHELL_VERBOSITY                                | 0                                                                                                                                                                           |
+------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
**Screenshots**

![Image](https://github.com/user-attachments/assets/020d2bd8-f7c7-4b36-bdae-f37cc6b97c04)
