### ISSUE TITLE
Have option to auto-sync without cronjob

### ISSUE THREAD

**Issue by Mx772** [dreeveapp/dreeve#6]
Would be nice to have it be able to autosync toggle (exposed via Env Var/UI) vs configuring a cronjob.

**Comment by pdoteter** [comment]
Some update here.  It's doable completely in docker by using the ofelia container

An example of my docker-compose.yml file:

```
services:
  scheduler:
    image: mcuadros/ofelia:latest
    restart: "unless-stopped"
    depends_on:
      - app
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/storage/strava/ofelia:/ofelia:rw
    labels:
      ofelia.save-folder: /ofelia
  app:
    image: robiningelbrecht/strava-statistics:latest
    env_file: ./.env
    volumes:
      - /srv/storage/strava/build:/var/www/build:rw
      - /srv/storage/strava/database:/var/www/storage/database:rw
      - /srv/storage/strava/files:/var/www/storage/files:rw
      - ./refresh.sh:/bin/refresh.sh
    ports:
      - 8180:8080
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.import.schedule: "0 0 2 * * *"
      ofelia.job-exec.import.command: "sh /bin/refresh.sh"
```

For ease of use I also created a refresh.sh which just does:

```
#sh
bin/console app:strava:import-data
bin/console app:strava:build-files
```

The configuration like this is that the scheduler container will look to all labels on all containers in docker.  And with this configuration it will simulate a docker exec with the parameters sh /bin/refresh.sh
which in the end will refresh and build the files at 2:00 AM

Hope this helps other people

One note: You can only have 1 scheduler container running I've noticed even, if used in an another compose file, that one will also do the job. But the documentation of ofelia is probably a good place to start than.
