### ISSUE TITLE
[FEAT] Allow to set the main activity for better dashboard view

### ISSUE THREAD

**Issue by edersong** [dreeveapp/dreeve#602]
**Is your feature request related to a problem? Please describe.**
Every time I enter in my app, need to change the view of any dashboard place to running to view my statistics.

**Describe the solution you'd like**
A configuration setting to set my favorite sport to be presented by dashboard at the first tab, so no need to change every time when I came to my dashboard to see my statistics

**Additional context**
N/A

**Comment by robiningelbrecht** [comment]
Hi @edersong, this is already possible by setting your "sport_types_to_import" in the correct order:

```yml
number_of_new_activities_to_process_per_import: 250
  # Sport types to import. Leave empty to import all sport types
  # With this list you can also decide the order the sport types will be rendered in.
  # A full list of allowed options is available on https://github.com/robiningelbrecht/statistics-for-strava/wiki/Supported-sport-types/
  sport_types_to_import: []
```
