### ISSUE TITLE
Syntax Error in Json.php line 16

### ISSUE THREAD

**Issue by sziyan** [dreeveapp/dreeve#61]
Greetings!

I am attempting to run this application in Kubernetes, and encountered the following error when importing data:

```
strava-statistics-7789b6fb5f-5zv28:/var/www/storage/database# /var/www/bin/console app:strava:import-data

In Json.php line 16:
                
  Syntax error            
```

```
strava-statistics-7789b6fb5f-5zv28:/var/www/storage/database# /var/www/bin/console app:strava:build-files

In Json.php line 16:
                
  Syntax error  

```

`strava.db` is only created after i run `bin/console app:strava:vacuum`
```
strava-statistics-7789b6fb5f-5zv28:/var/www/storage/database# ls -l
total 4
-rwxrwxrwx    1 root     root          4096 Dec 31 09:34 strava.db
```

My deployment manifest as below:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strava-statistics
spec:
  selector:
    matchLabels:
      app: strava-statistics
  template:
    metadata:
      labels:
        app: strava-statistics
    spec:
      volumes:
        - name: strava-statistics-pvc
          persistentVolumeClaim:
            claimName: strava-statistics-pvc
      initContainers:
        - name: init-permission
          image: busybox
          command: ['sh', '-c']
          args: ['chmod 777 -R /var/www/storage/database && chmod 777 -R /var/www/storage/files']
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
          - name: strava-statistics-pvc
            mountPath: /var/www/storage/database
            subPath: database
          - name: strava-statistics-pvc
            mountPath: /var/www/storage/files
            subPath: files
      containers:
      - name: strava-statistics
        image: robiningelbrecht/strava-statistics:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: strava-statistics
          - secretRef:
              name: strava-secret
        volumeMounts:
          - name: strava-statistics-pvc
            mountPath: /var/www/build
            subPath: build
          - name: strava-statistics-pvc
            mountPath: /var/www/storage/database
            subPath: database
          - name: strava-statistics-pvc
            mountPath: /var/www/storage/files
            subPath: files
```

The environment variables indicated in this project README are passed in via configMaps and Secrets.

Let me know if there are any information required for troubleshooting. Thanks!

**Comment by robiningelbrecht** [comment]
I think the environment variables are not valid json. Can you copy/paste what you configured there?

**Comment by sziyan** [comment]
Thanks for the response.

My configMap as below:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: strava-statistics
data:
  DATABASE_URL: "sqlite:///%kernel.project_dir%/storage/database/strava.db?charset=utf8mb4"
  STRAVA_CLIENT_ID: '143903'
  UNIT_SYSTEM: metric
  ACTIVITY_TYPES_TO_IMPORT: '["Ride", "VirtualRide", "Run"]'
  ATHLETE_BIRTHDAY: '1992-02-04'
  ATHLETE_WEIGHTS: | 
    '{
      "2024-12-01": 65.0,
      "2024-12-25": 66.0
    }'
  FTP_VALUES: | 
    '{
      "2024-12-01": 198,
      "2024-12-25": 220
    }'
```

This is what I see from inside the container:

```
strava-statistics-57b99c69cf-b4kxl:/var/www$ echo $ATHLETE_WEIGHTS
'{ "2024-12-01": 65.0, "2024-12-25": 66.0 }'
strava-statistics-57b99c69cf-b4kxl:/var/www$ echo $FTP_VALUES
'{ "2024-12-01": 198, "2024-12-25": 220 }'
```

**Comment by robiningelbrecht** [comment]
Can you try ATHLETE_WEIGHTS and FTP_VALUES without the pipes?

**Comment by sziyan** [comment]
Thanks, it worked now!

For future reference sake, this is how my configMap looks like now:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: strava-statistics
data:
  DATABASE_URL: "sqlite:///%kernel.project_dir%/storage/database/strava.db?charset=utf8mb4"
  STRAVA_CLIENT_ID: '143903'
  UNIT_SYSTEM: metric
  ACTIVITY_TYPES_TO_IMPORT: '["Ride", "VirtualRide", "Run"]'
  ATHLETE_BIRTHDAY: '1992-02-04'
  ATHLETE_WEIGHTS: '{ "2024-12-01": 65.0, "2024-12-25": 66.0 }'
  FTP_VALUES: '{ "2024-12-01": 198, "2024-12-25": 220 }'
```

Thanks for the quick help!
