### ISSUE TITLE
auto cron / import does not seem to be working

### ISSUE THREAD

**Issue by NimdaBE** [dreeveapp/dreeve#631]
hello,

i’ve setup SFS on portainer and manual import and manually building the files is working. But new activities on strava do not seem to get imported automatically by the auto cron.

At startup i see "Auto Cron: Set schedule to "0 18 * * *" in the logs, so it sees my environment variable that it should trigger at 18:00, but it never does (i’ve waited 2 days). There is also no other mention of cron in the logs so i don’t know if the cron is even trying to import and if so, if it’s failing at some point...

**Comment by robiningelbrecht** [comment]
hi @NimdaBE , can you check if you can see something in the log files located in `storage/files/logs/console-output-YYYY-MM-DD.log`?

If your auto cron runs at 18, there should be a trace in those logs. If not, then indeed, something is probably wrong

**Comment by NimdaBE** [comment]
hi, i just checked and the last entry in that file is from may 26th, the last time i manually imported activities...

**Comment by robiningelbrecht** [comment]
@NimdaBE Not sure how to fix this. Lots of people are using this and it just works. 
Have you tried "downing" your container and "upping" it again?

**Comment by NimdaBE** [comment]
i have deleted the container, set the time for 9:00 this morning and rebuild the container. The portainer log show Auto Cron: Set schedule to "0 9 * * *" but nothing happens after a few hours. The console output log does not change and still contains only the entries from a few days ago. All files and folders on the persistent storage are chmodded to 777 with the same UID and GID as owner as a set in the docker compose yml. The only thing i can think of is that maybe the cron job is looking for the .env file and because i use portainer i set the environment variables within the compose file and not using an external .env file? Running the import and build manually works...

My compose yml looks like this.

```
stravastats:
    image: robiningelbrecht/strava-statistics:latest
    container_name: statistics-for-strava
    restart: unless-stopped
    volumes:
      - /home/nimda/Dockers/stravastats/config:/var/www/config/app
      - /home/nimda/Dockers/stravastats/build:/var/www/build
      - /home/nimda/Dockers/stravastats/storage/database:/var/www/storage/database
      - /home/nimda/Dockers/stravastats/storage/files:/var/www/storage/files
    environment:
      - STRAVA_CLIENT_ID=redacted
      - STRAVA_CLIENT_SECRET=redacted
      - STRAVA_REFRESH_TOKEN=redacted
      - IMPORT_AND_BUILD_SCHEDULE="0 9 * * *"
      - TZ=Europe/Brussels
      - PUID=1000
      - PGID=1000
    ports:
      - 8080:8080
```
