### ISSUE TITLE
AthleteWeight for date "2022-09-22 00:00:00" not found  

### ISSUE THREAD

**Issue by sziyan** [dreeveapp/dreeve#64]
Hi, 

I am back again with some queries when attempting to deploy to Kubernetes 😄

When attempting to build the app, I encountered the following error:

```
strava-statistics-6c9d65c498-kpl9k:/var/www$ bin/console app:strava:build-files
Building HTML...
  => Calculating Eddington
  => Calculating weekday stats
  => Calculating daytime stats
  => Calculating monthly stats
  => Calculating best power outputs

In DbalAthleteWeightRepository.php line 47:
                                                          
  AthleteWeight for date "2022-09-22 00:00:00" not found  
                                                          

app:strava:build-files
```

My configMap as below:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: strava-statistics
data:
  DATABASE_URL: "sqlite:///%kernel.project_dir%/storage/database/strava.db?charset=utf8mb4"
  STRAVA_CLIENT_ID: '143903'
  UNIT_SYSTEM: metric
  ACTIVITY_TYPES_TO_IMPORT: '["Ride", "VirtualRide", "Run"]'
  ATHLETE_BIRTHDAY: '1992-02-04'
  ATHLETE_WEIGHTS: '{ "20223-09-22": 65.0, "2024-10-25": 66.0 }'
  FTP_VALUES: '{ "2023-09-22": 198, "2024-10-25": 220 }'
```

I did not configure 2022-09-22 in any of my secrets or configMap.

My deployment for reference:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strava-statistics
spec:
  selector:
    matchLabels:
      app: strava-statistics
  template:
    metadata:
      labels:
        app: strava-statistics
    spec:
      volumes:
        - name: strava-statistics-pvc
          persistentVolumeClaim:
            claimName: strava-statistics-pvc
      initContainers:
        - name: init-permission
          image: busybox:latest
          command: ['sh', '-c']
          args: ['chmod 777 -R /var/www/storage/database && chmod 777 -R /var/www/storage/files']
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
          - name: strava-statistics-pvc
            mountPath: /var/www/storage/database
            subPath: database
          - name: strava-statistics-pvc
            mountPath: /var/www/storage/files
            subPath: files
      containers:
      - name: strava-statistics
        image: robiningelbrecht/strava-statistics:v0.2.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: strava-statistics
          - secretRef:
              name: strava-secret
        volumeMounts:
          - name: strava-statistics-pvc
            mountPath: /var/www/build
            subPath: build
          - name: strava-statistics-pvc
            mountPath: /var/www/storage/database
            subPath: database
          - name: strava-statistics-pvc
            mountPath: /var/www/storage/files
            subPath: files
```

**Comment by sziyan** [comment]
I got it working by using the following configMap to match what was in the error:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: strava-statistics
data:
  DATABASE_URL: "sqlite:///%kernel.project_dir%/storage/database/strava.db?charset=utf8mb4"
  STRAVA_CLIENT_ID: '143903'
  UNIT_SYSTEM: metric
  ACTIVITY_TYPES_TO_IMPORT: '["Ride", "VirtualRide", "Run"]'
  ATHLETE_BIRTHDAY: '1992-02-04'
  ATHLETE_WEIGHTS: '{"2022-09-20": 65.5,"2024-10-25": 66.3}'
  FTP_VALUES: '{"2022-09-20": 198,"2024-10-25": 220}'
```

and re-run import-data and build-files.

Is this expected behavior?
