### ISSUE TITLE
Allow custom heart rate zones

### ISSUE THREAD

**Issue by TFellet** [dreeveapp/dreeve#680]
### Is your feature request related to a problem? Please describe

The current formula for calculating HR zones (5 zones from 50% to 100% by steps of 10%) is one of many ways of calculating HR zones, but in my case, having the Z2 between 60% and 70% of my max HR is too low.
It would be cool if the zones were customizable.

### Describe the solution you'd like

In the config.yaml file, a way to enter the start of each zone directly (e.g. [136, 148, 162, 176, 188]) and each zone range from the start to the next zone, or the max HR for the last zone.
Another possible solution would be to specify the start of each zone by the % of your max HR (e.g. [0.68, 0.74, 0.81, 0.88, 0.94], or [68, 74, 81, 88, 94].

**Comment by robiningelbrecht** [comment]
Hi @TFellet, correct me if I'm wrong, but we already have the possibility to set custom "maxHeartRateFormula". Which allows you to set your max heart rate based on date ranges. Your heart rate zones are determined by your max heart rate.

So that means that you are already able to set your heart rate zones based on your max heart rate no?

![Image](https://github.com/user-attachments/assets/fe378193-7b50-49e6-92b7-7007baab359e)

**Comment by TFellet** [comment]
From what I understand, you can change how your max HR is computed, but then the zone 1 will always be from 50% to 60% to your max HR, zone 2 from 60% to 70%, etc.
The feature I would find useful would be to say that your zone 1 ranges from 50% to let's say 65% of your max HR, zone 2 from 65% to 80%, and some other values for zones 3, 4 and 5.

**Comment by robiningelbrecht** [comment]
@TFellet this kinda makes sense I guess. I would suggest to use a % of your max heart rate?

```yml
zone1:
   - from: 0%
   - to: 50%
zone2:
  - from: 50%
  - to: 60%
 ..... 
```

**Comment by TFellet** [comment]
Yes this would be fine, in the solution I proposed I used an array to be more compact, but a solution like this would also works, do whatever is the easiest to implement 🙂

**Comment by robiningelbrecht** [comment]
@TFellet I want to do whatever is easiest to configure and use. A lot of users are not that tech-savvy so it needs to be very clear and expliciet

**Comment by TFellet** [comment]
In this case I would argue for a way to modify the config file directly from the interface but that's a different issue I guess

**Comment by robiningelbrecht** [comment]
@TFellet yeah, that's not going to happen any time soon. Started this a few weeks back and then realised that this would require user login as well.

**Comment by TFellet** [comment]
It's a really good project, and I find it very useful, thank you  for making it ;) 
I would have tried to help if it was Python or JS unfortunately I don't know PHP.

**Comment by robiningelbrecht** [comment]
Thanks :). Maybe it's an opportunity to learn PHP 😎 ?

**Comment by robiningelbrecht** [comment]
So I think the percentage approach is flawed. Your heart rate zones probably change over time as you get older, just like your max heart rate. That's why for max heart rate we force this to be set for date ranges:

![Image](https://github.com/user-attachments/assets/032e5e41-4000-4fb6-acd1-e112dd2205dd)

**Comment by TFellet** [comment]
The zones could also be set for a date range to stay consistent

**Comment by robiningelbrecht** [comment]
@TFellet Thought about this and I'm just going to add the possibility to set custom zone % ranges. No history

**Comment by gjvanzyl** [comment]
> [@TFellet](https://github.com/TFellet) this kinda makes sense I guess. I would suggest to use a % of your max heart rate?
> 
> zone1:
>    - from: 0%
>    - to: 50%
> zone2:
>   - from: 50%
>   - to: 60%
>  .....

I think percentages involve quite a bit of math. I'd dumb it down to actual beats per minute

zone1:
    - from: X bpm
    - to: Y bpm

zone2:
   -from: X bpm
   -to: Y bpm


....

**Comment by robiningelbrecht** [comment]
@gjvanzyl using absolute values is not a good idea imo. If we use percentages and your max heat rate changes, the heart rate zones will move with it. Which is what we want I think. Your heart rate zones are never absolute for the entirety of your life?

**Comment by gjvanzyl** [comment]
@robiningelbrecht this assumes that current formula being used to calculate zones use a percentage "Max HR". There are alternatives that use your lactate threshold as an example. 

In my case I have gone for blood lactate testing while running at set paces to get more precise zone metrics and my Z2 vs Z3 vs Z4+ all vary in width. 

Giving an option to use absolute values or "override" avoids having to program the app to be aware of alternative zone mapping algorithms. 

Another rabbit hole, is that your zones can differ based on the sport/activity like Running vs Cycling, but lets leave that dog sleeping for now.

**Comment by robiningelbrecht** [comment]
@gjvanzyl Well, it would be easier to implement "Heart rate zones per activity type" from the start instead of adding them later on...

**Comment by AoifeSidhe** [comment]
A very necessary feature! I'm missing the custom heart rate zones.
The division by sport is a great idea also; I’d love to see swimming, running, and cycling profiles :)
Although I like the idea of adding the LT (lactate threshold) as a method for calculating zones, in my opinion, this creates unnecessary complexity in the code. Percentages of max heart rate work perfectly fine. :)

And if you do want to add a toggle, maybe it could be between this method and absolute numbers, so that we don’t have to calculate percentages to get the correct numbers.

Why am I in favor of this approach? Because we’re already entering absolute weight values, and similarly, we should update our max HR figures if we’re not using standard age-based formulas :)
So for nerds like me, who are ready to run around with a lactate meter, updating the zone table won’t be difficult at all!
And everyone else just won’t bother using it.

**Comment by robiningelbrecht** [comment]
@AoifeSidhe I think the heart rate zones per activity type still don't cover everything actually.

Let's say you set some ranges today. 6 months from now you change the ranges because reasons. This means that all activities will use this new range even those in past. Which, I think, is not correct...

If we want to do this correct, I think we need to be able to set heart rate zones per activity type per date range (similar to weight history)

**Comment by AoifeSidhe** [comment]
`If we want to do this correct, I think we need to be able to set heart rate zones per activity type per date range (similar to weight history)`

@robiningelbrecht 
Yep, that’s exactly what I was thinking!
But while weight stays the same for all activities, we can have different "HR zones histories" for different types of activities. :)

The only thing that seems complicated is the configuration — will it be mandatory to have profiles for all activities? What if someone wants to use only custom zones but not separate them by activity type?

**Comment by robiningelbrecht** [comment]
@AoifeSidhe I could implement something like this

```yml
heartRateZones:
  mode: percentage/absolute
  # Will be used when there's no specific zone found for an activity type or date 
  default:
     zone1:
       - from: 0%
       - to: 50%
     zone2:
       - from: 50%
       - to: 60%
   run:
      # Will be used when there's no specific zone found for date 
      default: # Zone config
      2020-01-01: # Zone config
      2021-03-01: # Zone config
   bike:
      # Will be used when there's no specific zone found for date 
      default: # Zone config
      2020-01-01: # Zone config
      2021-03-01: # Zone config
```

This is a VERY complex configuration and I'm not sure if we want to go this far?

**Comment by gjvanzyl** [comment]
Alternative proposal. 

Can we pull the HR zones directly from Strava API and date stamp them into a daily HR Zone tracked table for evaluation by the app. This way the zones you configure in Strava pull right through to the app and is date stamped. 

Edit in Strava and upon next sync, the updated HR is automatically updated. 

Seems possible? 

https://developers.strava.com/docs/reference/#api-Athletes-getLoggedInAthleteZones

**Comment by AoifeSidhe** [comment]
> This is a VERY complex configuration and I'm not sure if we want to go this far?

Seems fine to me, but I see where things started to get complicated.
Maybe we should keep only custom/model toggle since that's the most important feature.

@gjvanzyl 
Also, there’s no option for swim or bike HR zones on Strava — or am I wrong?
I definitely remember seeing them in TrainingPeaks, but that’s another story :)

**Comment by robiningelbrecht** [comment]
@gjvanzyl pulling in the data from Strava is not an option in my opinion as we can't fetch historical zones. This would mean that we have to combine Strava zones with manual configured zones. A disaster waiting to happen if you ask me. Had the exact same discussion in another issue but about "weights" :) 

@AoifeSidhe 

> Maybe we should keep only custom/model toggle since that's the most important feature.

Not sure if I understand?

**Comment by AoifeSidhe** [comment]
@robiningelbrecht 
I'm saying that if splitting into custom zones by sport type requires overly complex logic, then the main thing (IMHO) is to implement the option to either calculate them as now using one of the age-based models, or to use user-defined custom values. :)

But again, I want to repeat that I think the logic from the example is excellent. :)
Complex, but good)

**Comment by robiningelbrecht** [comment]
Came up with this, what do you think?

```yml
    heartRateZones:
      # Relative or absolute. 
      # Relative will treat the zone numbers as percentages based on your max heart rate, while absolute will treat them as actual heartbeats per minute.
      # This mode will apply to all heart rate zones you define.
      mode: relative
      # The default zones for all activities.
      # If you have specified date ranges, this one will be used when there's no exact match for the activity date.
      default:
        zone1:
          - from: 0
          - to: 60
        zone2:
          - from: 61
          - to: 70
        zone3:
          - from: 71
          - to: 80
        zone4:
          - from: 81
          - to: 90
        zone5:
          - from: 91
          - to: null # Infinity and beyond.
      # You can further refine your zones by specifying date ranges.
      # This works the same way as weight and FTP history: https://statistics-for-strava-docs.robiningelbrecht.be/#/configuration/main-configuration?id=athlete-weight-historys
      dateRanges:
        "2025-01-01": ...
        "2024-11-08": ...
        # You can also override your heart rate zones for specific sport types.    
        # A full list of allowed options is available on https://statistics-for-strava-docs.robiningelbrecht.be/#/configuration/main-configuration?id=supported-sport-types      
        sportTypes:
          GravelRide:
            # The default heart rate zones for all GravelRide activities.
            # If you have specified date ranges, this one will be used when there's no exact match for the activity date.
            default: ...
            dateRanges:
              "2025-01-01": ...
              "2024-11-08": ...
```
