### ISSUE TITLE
Crontab line is defined with quotes (") for the time definition which causes the scheduled task not triggered.

### ISSUE THREAD

**Issue by tuantub** [dreeveapp/dreeve#690]
### Describe the bug

If your configure the crontab setting with:
```IMPORT_AND_BUILD_SCHEDULE="5 4 * * *"```
then the crontab line will look like:
```"5 4 * * *" printf "AUTO CRON" && printf " Importing Strava Data\n" && cd /var/www && bin/console app:strava:import-data && printf "Building HTML\n" && bin/console app:strava:build-files```
which will never trigger the crontab.
The crontab line shall look like:
```5 4 * * * printf "AUTO CRON" && printf " Importing Strava Data\n" && cd /var/www && bin/console app:strava:import-data && printf "Building HTML\n" && bin/console app:strava:build-files```
to be valid.

### Expected behavior

Import commands to be triggered with crontab

### Provide your docker compose config

```yml
version: '3'
services:
  strava-statistic:
    image: robiningelbrecht/strava-statistics:latest
    container_name: statistics-for-strava
    restart: unless-stopped
    volumes:
      - ./config:/var/www/config/app
      - ./build:/var/www/build
      - ./storage/database:/var/www/storage/database
      - ./storage/files:/var/www/storage/files
    env_file: ./.env
    ports:
      - 8888:8080
```

### Environment configuration

```yml
# The client id of your Strava app.
STRAVA_CLIENT_ID=MY_ID
# The client secret of your Strava app.
STRAVA_CLIENT_SECRET=SECRET
# You will need to obtain this token the first time you launch the app.
# Leave this unchanged for now until the app tells you otherwise.
# Do not use the refresh token displayed on your Strava API settings page, it will not work.
STRAVA_REFRESH_TOKEN=TOKEN


# The schedule to periodically run the import and HTML builds. Leave empty to disable periodic imports.
# The default schedule runs once a day at 04:05. If you do not know what cron expressions are, please leave this unchanged
# Make sure you don't run the imports too much to avoid hitting the Strava API rate limit. Once a day should be enough.
IMPORT_AND_BUILD_SCHEDULE="5 4 * * *"
# Valid timezones can found under TZ Identifier column here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Asia/Saigon
#TZ=Etc/GMT

# The UID and GID to create/own files managed by statistics-for-strava
PUID=1000
PGID=1000
```

System Information:
- OS: Ubuntu 20.04.6 
- Kernel:  5.4.0-215-generic 235-Ubuntu SMP Fri Apr 11 21:55:32 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
- Docker:
 ```
Client:
 Version:           26.1.3
 API version:       1.45
 Go version:        go1.22.2
 Git commit:        26.1.3-0ubuntu1~20.04.1
 Built:             Mon Oct 14 22:06:01 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          26.1.3
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.22.2
  Git commit:       26.1.3-0ubuntu1~20.04.1
  Built:            Mon Oct 14 22:06:01 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.24
  GitCommit:
 runc:
  Version:          1.1.12-0ubuntu2~20.04.1
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
```
