### ISSUE TITLE
Weird Gear Photo Sizing on Desktop and Mobile Safari

### ISSUE THREAD

**Issue by oddish3** [dreeveapp/dreeve#692]
(Desktop)
Firefox:
![Image](https://github.com/user-attachments/assets/1f23d4f0-fe0d-45f1-bef9-040456e77f77)
Safari:
![Image](https://github.com/user-attachments/assets/2efc5f77-0084-4374-b67b-7a96b2a66b5c)
![Image](https://github.com/user-attachments/assets/e880e383-6055-4ee3-a7b0-0c29a7a0e83a)

```
enabled: true
hashtagPrefix: 'sfs'
components:
  - tag: 'bike-chain'
    label: 'Chain & groupset'
    imgSrc: 'chain.png'
    attachedTo:
      - '15971224'
    maintenance:
      - tag: lubed
        label: Lube
        interval:
          value: 300
          unit: km
      - tag: replaced
        label: Replace
        interval:
          value: 1900
          unit: km
  - tag: 'bike-tyres'
    label: 'Ultra Sport III'
    imgSrc: 'tyre.jpeg'
    attachedTo:
      - '15971224'
    maintenance:
      - tag: replaced
        label: Replace
        interval:
          value: 2500
          unit: km
  - tag: 'running-shoes'
    label: 'Asics Gel Flux 8'
    imgSrc: 'shoe.avif'
    attachedTo: 
      - '23696729'
    maintenance:
      - tag: replaced 
        label: Replace 
        interval:
          value: 650
          unit: km
gears:
  - gearId: '15971224'
    imgSrc: 'spec.png'
  - gearId: '23696729'
    imgSrc: 'shoe.avif'

```
