### ISSUE TITLE
Exception During Rendering of a Template - Must be of Type String, Null Given

### ISSUE THREAD

**Issue by chrisfeagles** [dreeveapp/dreeve#765]
### Describe the bug

First off - Thank you for building and supporting this project! 

When trying to run build-files command - I am receiving a set of errors:

`
Configuring locale...
Building Manifest...
Building App...
  => Building index
  => Building dashboard

In activity-title.html.twig line 12:
                                                                                                          
  An exception has been thrown during the rendering of a template ("App\Infrastructure\Twig\RenderTempla  
  teTwigExtension::renderSvg(): Argument #1 ($template) must be of type string, null given, called in /v  
  ar/www/var/cache/dev/twig/c8/c8848086881ae63e2d8e0ffeaa1e59d7.php on line 81") in "html/component/acti  
  vity-title.html.twig" at line 12.                                                                       
                                                                                                          

In RenderTemplateTwigExtension.php line 28:
                                                                                                          
  App\Infrastructure\Twig\RenderTemplateTwigExtension::renderSvg(): Argument #1 ($template) must be of t  
  ype string, null given, called in /var/www/var/cache/dev/twig/c8/c8848086881ae63e2d8e0ffeaa1e59d7.php   
  on line 81                                                                                              
                                                                                                          
`

This started the other day when I upgraded to 2.3.0 and tried to add custom heart rate zones.  I copied the new config and made changes based on heart rate zones I had from Apple Watch/Strava.  I tried pulling 2.3.2 this morning to see if there was a resolved bug but still getting the error.

### Expected behavior

Successful build of files

### Provide your docker compose config

```yml
services:
  app:
    image: robiningelbrecht/strava-statistics:v2.3.2
    container_name: statistics-for-strava
    restart: unless-stopped
    volumes:
      -  ./config:/var/www/config/app
      -  ./build:/var/www/build
      -  ./storage/database:/var/www/storage/database
      -  ./storage/files:/var/www/storage/files
    env_file: ./.env
    ports:
      - 8080:8080
```

### Environment configuration

```yml
Statistics for Strava
=====================

 Please copy all this output into the description of the bug ticket

                                                                                                                        
 [WARNING] Do not forget to redact sensitive information                                                                
                                                                                                                        

+---------------------------+-----------------------------------------------------+
| ENV variable              | Value                                               |
+---------------------------+-----------------------------------------------------+
| APP_VERSION               | v2.3.2                                              |
| STRAVA_CLIENT_ID          | (REDACTED)                                          |
| STRAVA_CLIENT_SECRET      | (REDACTED)                                          |
| STRAVA_REFRESH_TOKEN      | (REDACTED)                                          |
| IMPORT_AND_BUILD_SCHEDULE | 5 4 * * *                                           |
| TZ                        | America/Chicago                                     |
+---------------------------+-----------------------------------------------------+
| APP_CONFIG_GENERAL        | {                                                   |
|                           |     "appUrl": "(REDACTED)",      |
|                           |     "profilePictureUrl": null,                      |
|                           |     "ntfyUrl": null,                                |
|                           |     "athlete": {                                    |
|                           |         "birthday": "(REDACTED)",                   |
|                           |         "maxHeartRateFormula": "fox",               |
|                           |         "heartRateZones": {                         |
|                           |             "mode": "relative",                     |
|                           |             "default": {                            |
|                           |                 "zone1": {                          |
|                           |                     "from": 50,                     |
|                           |                     "to": 70                        |
|                           |                 },                                  |
|                           |                 "zone2": {                          |
|                           |                     "from": 71,                     |
|                           |                     "to": 77                        |
|                           |                 },                                  |
|                           |                 "zone3": {                          |
|                           |                     "from": 78,                     |
|                           |                     "to": 84                        |
|                           |                 },                                  |
|                           |                 "zone4": {                          |
|                           |                     "from": 85,                     |
|                           |                     "to": 91                        |
|                           |                 },                                  |
|                           |                 "zone5": {                          |
|                           |                     "from": 92,                     |
|                           |                     "to": null                      |
|                           |                 }                                   |
|                           |             }                                       |
|                           |         },                                          |
|                           |         "weightHistory": {                          |
|                           |             "2025-05-15": 188.3,                    |
|                           |             "2024-01-01": 191.1,                    |
|                           |             "2023-12-20": 195,                      |
|                           |             "2023-09-08": 189.5,                    |
|                           |             "2022-09-18": 191.4,                    |
|                           |             "2021-09-15": 203.5                     |
|                           |         },                                          |
|                           |         "ftpHistory": []                            |
|                           |     }                                               |
|                           | }                                                   |
+---------------------------+-----------------------------------------------------+
| APP_CONFIG_IMPORT         | {                                                   |
|                           |     "numberOfNewActivitiesToProcessPerImport": 250, |
|                           |     "sportTypesToImport": [                         |
|                           |         "Run"                                       |
|                           |     ],                                              |
|                           |     "activityVisibilitiesToImport": [],             |
|                           |     "skipActivitiesRecordedBefore": null,           |
|                           |     "activitiesToSkipDuringImport": []              |
|                           | }                                                   |
+---------------------------+-----------------------------------------------------+
| APP_CONFIG_APPEARANCE     | {                                                   |
|                           |     "locale": "en_US",                              |
|                           |     "unitSystem": "imperial",                       |
|                           |     "timeFormat": 24,                               |
|                           |     "dateFormat": "MONTH-DAY-YEAR"                  |
|                           | }                                                   |
+---------------------------+-----------------------------------------------------+
| APP_CONFIG_ZWIFT          | {                                                   |
|                           |     "level": null,                                  |
|                           |     "racingScore": null                             |
|                           | }                                                   |
+---------------------------+-----------------------------------------------------+
```

**Comment by robiningelbrecht** [comment]
@chrisfeagles Could you check in your database what the sport types of the last imported activities are please?

**Comment by chrisfeagles** [comment]
I assume you mean the Activity table - sorting by startDateTime the last activity is "Run".  The only types in this table are "Run"

**Comment by robiningelbrecht** [comment]
Hmmm very weird. I can't reproduce this. Would you be willing to send me your database so I can properly investigate this?

**Comment by chrisfeagles** [comment]
Is there anything I can do on my side to help troubleshooting before sending the data?

**Comment by robiningelbrecht** [comment]
Do you know how to query the `strava.db` file?

If so, can you execute:

```sql
SELECT DISTINCT sportType FROM Activity
```

And share the result?

**Comment by chrisfeagles** [comment]
Yes - I copied the strava.db to my laptop and have it open in SQLite browser.  

Executed SQL - it returned a single row: "Run"

**Comment by robiningelbrecht** [comment]
The plot thickens....
I'm afraid I'll need proper data to be able to debug this. The good thing is, I probably only need data from the `Activity` table to do this.
So you could get rid of 95% of data in your database before you send it over to me... is that an option for you?

**Comment by chrisfeagles** [comment]
Sure - please provide any instructions on what to do and where to send it.

**Comment by robiningelbrecht** [comment]
Ok, so just run following queries. These should remove all data I don't need to properly debug:

```sql
DELETE FROM ActivityBestEffort
DELETE FROM ActivityLap
DELETE FROM ActivitySplit
DELETE FROM ActivityStream
DELETE FROM Challenge
DELETE FROM CombinedActivityStream
DELETE FROM Segment
DELETE FROM SegmentEffort
UPDATE Activity SET data = '{}'
```

You can email me the result on ingebrechtrobin@gmail.com

**Comment by chrisfeagles** [comment]
Sent!

**Comment by robiningelbrecht** [comment]
Works perfectly fine for me. This is so weird, I don't understand at all.

![Image](https://github.com/user-attachments/assets/c68a1acd-bf35-48ec-9d4d-f367500e660a)

Have you tried re-pulling the docker image?

**Comment by robiningelbrecht** [comment]
@chrisfeagles Can you share your complete `config.yaml`? You can leave out sensitive info, like appUrl or birtdayDay

**Comment by chrisfeagles** [comment]
@robiningelbrecht see below for config.  This started on v2.3.0 - I tried to add the new heart rate zones.  I updated my config.yaml, then ran the import and build commands.  Import went fine with no issues, the build commands started getting the failure.  

I left it for a couple days, came back and pulled v2.3.2, copied the default config from the documentation and input my info incase I had a typo in my modified version.  I am going to copy my config over to a new docker instance and try to rebuild from scratch to see what happens.  I'll let it pull a few runs from the API and build everything new.  

```yaml
general:
  # The URL on which the app will be hosted. This URL will be used in the manifest file. 
  # This will allow you to install the web app as a native app on your device.
  appUrl: (REDACTED)
  # Optional, a link to your profile picture. Will be used to display in the nav bar and link to your Strava profile.
  # Leave empty to disable this feature.
  profilePictureUrl: null
  # Optional, full URL with ntfy topic included. This topic will be used to notify you when a new HTML build has run.
  # Leave empty to disable notifications.
  ntfyUrl: null
  athlete:
    # Your birthday. Needed to calculate heart rate zones.
    birthday: (REDACTED)
    # The formula used to calculate your max heart rate. The default is Fox (220 - age).
    # Allowed values: arena, astrand, fox, gellish, nes, tanaka (https://pmc.ncbi.nlm.nih.gov/articles/PMC7523886/table/t2-ijes-13-7-1242/)
    # Or you can set a fixed number for any given date range.  
    maxHeartRateFormula: 'fox'
    # If you're not sure about your zones, leave this unchanged — the defaults are sensible.
    heartRateZones:
      # Relative or absolute. 
      # Relative will treat the zone numbers as percentages based on your max heart rate, while absolute will treat them as actual heartbeats per minute.
      # This mode will apply to all heart rate zones you define.
      mode: relative
      # The default zones for all activities.
      default:
        zone1:
          from: 50
          to: 70
        zone2:
          from: 71
          to: 77
        zone3:
          from: 78
          to: 84
        zone4:
          from: 85
          to: 91
        zone5:
          from: 92
          to: null # Infinity and beyond.
      # 🔥 PRO tip: You can further refine your heart rate zones by specifying date ranges and sport types.
      #    Read more about the possibilities on https://statistics-for-strava-docs.robiningelbrecht.be/#/configuration/main-configuration?id=athlete-heart-rate-zones
    # maxHeartRateFormula:
    #    "2020-01-01": 198
    #    "2025-01-10": 193
    # History of weight (in kg or pounds, depending on appearance.unitSystem). Needed to calculate relative w/kg.
    # Make sure to replace the YYYY-MM-DD examples with your own weight history.
    # Read more about the weight history on https://statistics-for-strava-docs.robiningelbrecht.be/#/configuration/main-configuration?id=athlete-weight-history
    weightHistory:
      "2025-05-15": 188.3
      "2024-01-01": 191.1
      "2023-12-20": 195.0
      "2023-09-08": 189.5
      "2022-09-18": 191.4
      "2021-09-15": 203.5
    # Optional, history of FTP. Needed to calculate activity stress level.
    # ftpHistory
    #    "2024-10-03": 198
    #    "2025-01-10": 220
    #
    ftpHistory: []
appearance:
  # Allowed options: en_US, fr_FR, nl_BE, de_DE, pt_BR, pt_PT or zh_CN
  locale: 'en_US'
  # Allowed options: metric or imperial
  unitSystem: 'imperial'
  # Time format to use when rendering the app
  # Allowed formats: 24 or 12 (includes AM and PM)
  timeFormat: 24
  # Date format to use when rendering the app
  # Allowed formats: DAY-MONTH-YEAR or MONTH-DAY-YEAR
  dateFormat: 'MONTH-DAY-YEAR'
import:
  # Strava API has rate limits (https://statistics-for-strava-docs.robiningelbrecht.be/#/troubleshooting/faq?id=why-does-it-take-so-long-to-import-my-data),
  # to make sure we don't hit the rate limit, we want to cap the number of new activities processed
  # per import. Considering there's a 1000 request per day limit and importing one new activity can
  # take up to 3 API calls, 250 should be a safe number.
  numberOfNewActivitiesToProcessPerImport: 250
  # Sport types to import. Leave empty to import all sport types
  # With this list you can also decide the order the sport types will be rendered in.
  # A full list of allowed options is available on https://statistics-for-strava-docs.robiningelbrecht.be/#/configuration/main-configuration?id=supported-sport-types 
  sportTypesToImport: [Run]
  # Activity visibilities to import. Leave empty to import all visibilities
  # This list can be combined with sportTypesToImport.
  # Allowed values: ["everyone", "followers_only", "only_me"]
  activityVisibilitiesToImport: []
  # Optional, the date (YYYY-MM-DD) from which you want to start importing activities. 
  # Any activity recorded before this date, will not be imported.
  # This can be used if you want to skip the import of older activities. Leave empty to disable.
  skipActivitiesRecordedBefore: null
  # An array of activity ids to skip during import. 
  # This allows you to skip specific activities during import.
  # ["123456789", "987654321"]
  activitiesToSkipDuringImport: []
metrics:
  # By default, the app calculates your Eddington score for Rides, Runs, and Walks.
  # Each category includes a list of sport types used in the calculation.
  # This setting lets you customize which sport types are grouped together and how the Eddington score is calculated.
  # If you're not familiar with the Eddington score, it's best to leave this as is for now and explore it once the app is running.
  # 🔥 PRO tip: it's possible to use the same sport type over multiple eddington numbers.
  eddington:
      # The label to be used for the tabs on the Eddington page.
    - label: 'Ride'
      # A boolean to indicate if this score should be displayed in the side navigation.
      # You can only enable two of these at the same time.
      showInNavBar: true
      # The sport types to include in the Eddington score for this tab.
      # Only sport types that belong to the same activity type (category) can be combined.
      # For a complete list of supported sport and activity types, visit: https://statistics-for-strava-docs.robiningelbrecht.be/#/configuration/main-configuration?id=supported-sport-types
      sportTypesToInclude: ['Ride', 'MountainBikeRide', 'GravelRide', 'VirtualRide']
    - label: 'Run'
      showInNavBar: true
      sportTypesToInclude: ['Run', 'TrailRun', 'VirtualRun']
    - label: 'Walk'
      showInNavBar: false
      sportTypesToInclude: ['Walk', 'Hike']
zwift:
  # Optional, your Zwift level (1 - 100). Will be used to render your Zwift badge. Leave empty to disable this feature
  level: null
  # Optional, your Zwift racing score (0 - 1000). Will be used to add to your Zwift badge if zwift.level is filled out.
  racingScore: null


```
