### ISSUE TITLE
Add custom consistency challenges

### ISSUE THREAD

**Issue by robohead456** [dreeveapp/dreeve#786]
### Is your feature request related to a problem? Please describe

It would be nice to have a way to add custom consistency goals through the config file to track personal goals. Currently the only way to do this is through editing the PHP files.

### Describe the solution you'd like

The only activity types tracked for consistency goals currently are runs and rides, but it would be nice to re-use the custom activity type labels from the eddington feature along with some common goal types (number of activities, distance, elevation, time) to be able to create custom goals in the config file. For an example I could define a walk and hike activity as:

```
- label: 'Walk'
      showInNavBar: false
      sportTypesToInclude: ['Walk', 'Hike']
- label: 'Hike'
      showInNavBar: false
      sportTypesToInclude: ['Hike']
```
and later on define goals such as:
```
- label: 'Hike at least 20mi per month'
      sportType: 'Hike'
      goalType: 'Distance'
      goalvalue: 20
- label: 'Go for 10 walks per month'
      sportType: 'Walk'
      goalType: 'Quantity'
      goalvalue: 10
```

As a bonus request, it would be great to convert the existing consistency goals into this format so that users can remove goals they do not consistently try for. For example if I ran a half marathon 5 years ago and never did it again it would be nice to have it not showing up in the consistency goals section and if this were defined as a goal in the config file I could just delete it.

**Comment by robohead456** [comment]
As a note: Strava does have "goals" as a premium feature, but the goals can only be hours/distance (not both) for the current week and/or the current year. I think that since the consistency goals are monthly only we would avoid implementing Strava premium features. Strava also only allows running or riding goals, not custom ones for different activity types.

If you think that these would implement sufficiently different/better customization it would be great to also have weekly/yearly consistency goals too, but I understand not wanting to cause problems by implementing Strava's premium features.

**Comment by robiningelbrecht** [comment]
@robohead456 thanks for the heads up and your feature request. We definitely won't be implementing Strava premium features, so the weekly/yearly consistency goals are off the table
But I am willing to make the current ones configurable like you suggested

**Comment by robiningelbrecht** [comment]
@robohead456 came up with this config. What do you think?

```yaml
  consistencyChallenges:
    - label: 'Ride a total of 200km'
      enabled: true
      type: 'distance'
      unit: 'kilometer'
      goal: 200
      sportTypesToInclude: ['Ride', 'MountainBikeRide', 'GravelRide', 'VirtualRide']
    - label: 'Ride a total of 600km'
      enabled: true
      type: 'distance'
      unit: 'kilometer'
      goal: 600
      sportTypesToInclude: ['Ride', 'MountainBikeRide', 'GravelRide', 'VirtualRide']
    - label: 'Ride a total of 1250km'
      enabled: true
      type: 'distance'
      unit: 'kilometer'
      goal: 1250
      sportTypesToInclude: ['Ride', 'MountainBikeRide', 'GravelRide', 'VirtualRide']
    - label: 'Complete a 100km ride'
      enabled: true
      type: 'distanceInOneActivity'
      unit: 'kilometer'
      goal: 100
      sportTypesToInclude: ['Ride', 'MountainBikeRide', 'GravelRide', 'VirtualRide']
    - label: 'Climb a total of 7500m'
      enabled: true
      type: 'altitude'
      unit: 'meter'
      goal: 7500
      sportTypesToInclude: ['Ride', 'MountainBikeRide', 'GravelRide', 'VirtualRide']
    - label: 'Complete a 5 km run'
      enabled: true
      type: 'distanceInOneActivity'
      unit: 'kilometer'
      goal: 5
      sportTypesToInclude: ['Run', 'TrailRun', 'VirtualRun']
    - label: 'Complete a 10 km run'
      enabled: true
      type: 'distanceInOneActivity'
      unit: 'kilometer'
      goal: 10
      sportTypesToInclude: ['Run', 'TrailRun', 'VirtualRun']
    - label: 'Complete a half marathon run'
      enabled: true
      type: 'distanceInOneActivity'
      unit: 'kilometer'
      goal: 21.1
      sportTypesToInclude: ['Run', 'TrailRun', 'VirtualRun']     
    - label: 'Run a total of 100km'
      enabled: true
      type: 'distance'
      unit: 'kilometer'
      goal: 100
      sportTypesToInclude: ['Run', 'TrailRun', 'VirtualRun']
    - label: 'Climb a total of 2000m'
      enabled: true
      type: 'altitude'
      unit: 'meter'
      goal: 2000
      sportTypesToInclude: ['Run', 'TrailRun', 'VirtualRun']
```
