### ISSUE TITLE
Error: "max(): Argument #1 must contain at least one element" when building files

### ISSUE THREAD

**Issue by giacomo-folli** [dreeveapp/dreeve#79]
Hi, first of all, thank you for this wonderful project! I appreciate all the effort you’ve put into building it.

I followed the installation guide up to the `⚡️Import and build statistics` section.
I encountered an issue while running the command `docker compose exec app bin/console app:strava:build-files` on my system, after importing strava data. Here are the details:

**System Information:**
- **OS:** Linux Ubuntu Server 24.0 LTS  
- **RAM:** 4GB
- **Docker Version:**  27.4.1, build b9d17ea

**Error Details:**  
During the `build-files` process, I received the following error:  
```
An exception has been thrown during the rendering of a template ("max(): Argument #1 ($value) must contain at least one element").
```

This appears in two locations:
1. **dashboard.html.twig** at **line 418**
2. **Collection.php** at **line 172**

I’ve attached a screenshot of the error for reference:  
<img width="916" alt="strava_error" src="https://github.com/user-attachments/assets/94742ea4-8c8a-40cd-8ea8-2a57f5dc11fc" />

Here are my `docker-compose.yml` and `.env` files:
*.env:* 
```
DATABASE_URL="sqlite:///%kernel.project_dir%/storage/database/strava.db?charset=utf8mb4"

STRAVA_CLIENT_ID=[MY_CLIENT_ID]
STRAVA_CLIENT_SECRET=[MY_CLIENT_SECRET]
STRAVA_REFRESH_TOKEN=[MY_REFRESH_TOKEN]

UNIT_SYSTEM=metric
ACTIVITY_TYPES_TO_IMPORT='["Run", "Ride", "VirtualRide"]'
ATHLETE_BIRTHDAY=[MY_BIRTHDAY]
ATHLETE_WEIGHTS='{
        "2025-01-01": 91.0
}'
FTP_VALUES='{
    "2024-11-21": 243,
    "2023-04-03": 209,
    "2023-01-01": 200
}'
```

*docker-compose.yml:* 
```
services:
  app:
    image: robiningelbrecht/strava-statistics:latest
    volumes:
      - ./build:/var/www/build
      - ./storage/database:/var/www/storage/database
      - ./storage/files:/var/www/storage/files
    env_file: ./.env
    ports:
      - 8081:8080
```

**Additional Notes:**  
It seems like the `max()` function is being called with an empty array. Could this be due to missing or incomplete data in my Strava account, or perhaps a default fallback value isn’t being provided in the code?

Let me know if there’s any more information I can provide or steps I can try to debug further. Thanks again for the fantastic project, and I look forward to your guidance on resolving this issue.

Best regards,  
Giacomo
