### ISSUE TITLE
Consistency Challenges In wrong order

### ISSUE THREAD

**Issue by oddish3** [dreeveapp/dreeve#795]
### Describe the bug

I ran a 10k in the june 2025, but this doesnt show up in consistency challenges, or if it does, it's labelled as being at the start of my strava history (and thus the labelling of dates in consistency challenges is wrong)

<img width="584" alt="Image" src="https://github.com/user-attachments/assets/4dec29b5-0afc-4f30-b912-360505af1ec9" />

I'm pretty sure this is my stats for the most recent time period (and i would prefer to see that by default, rather than the start of strava history)

Also this is the consistency challenges part of my config.yaml, but i only get the first 3 challenges (rather than all)
```
consistencyChallenges:
    - label: 'Complete a 5 km run'
      enabled: true
      type: 'distanceInOneActivity'
      unit: 'km'
      goal: 5
      sportTypesToInclude: ['Run', 'TrailRun', 'VirtualRun']
    - label: 'Complete a 10 km run'
      enabled: true
      type: 'distanceInOneActivity'
      unit: 'km'
      goal: 10
      sportTypesToInclude: ['Run', 'TrailRun', 'VirtualRun']
    - label: 'Complete a half marathon run'
      enabled: true
      type: 'distanceInOneActivity'
      unit: 'km'
      goal: 21.1
      sportTypesToInclude: ['Run', 'TrailRun', 'VirtualRun']
    - label: 'Run a total of 50km'
      enabled: true
      type: 'distance'
      unit: 'km'
      goal: 50
      sportTypesToInclude: ['Run', 'TrailRun', 'VirtualRun']
    - label: 'Run a total of 150km'
      enabled: true
      type: 'distance'
      unit: 'km'
      goal: 150
      sportTypesToInclude: ['Run', 'TrailRun', 'VirtualRun']
    - label: 'Run a total of 300km'
      enabled: true
      type: 'distance'
      unit: 'km'
      goal: 300
      sportTypesToInclude: ['Run', 'TrailRun', 'VirtualRun']
    - label: 'Climb a total of 2000m'
      enabled: true
      type: 'elevation'
      unit: 'm'
      goal: 2000
      sportTypesToInclude: ['Run', 'TrailRun', 'VirtualRun']
```

### Expected behavior

1. consistency challenges should reflect your activity dates correctly
2. consisntency cchallenge in dashboard should be ordered by most recent time (eg june 2025 to start)
3. all challenges defined in my config.yaml section should be valid

### Provide your docker compose config

```yml
/
```

### Environment configuration

```yml
/
```
