### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by robklingler** [dreeveapp/dreeve#89]
**Describe the bug**
Getting a 401 Unauthorized error when attempting to import.

**Tell us which app version you are on**
`v0.2.9`

**To Reproduce**
I have completed the Strava app authorization process, and was even able to refresh my token through a curl request, so I believe the client ID, client secret, and refresh token are all correct.  I've also re-authorized several times (updating refresh token each time, but no change in error message.)

**Expected behavior**
Expect syncing to at least start.  I have a lot of activities, so expect it to take a while, but can't even get started.

**Provide your docker compose config**
services:
```
  app:
    image: robiningelbrecht/strava-statistics:latest
    container_name: strava
    volumes:
      - /home/klingler/docker/strava/build:/var/www/build
      - /home/klingler/docker/strava/storage/database:/var/www/storage/database
      - /home/klingler/docker/strava/storage/files:/var/www/storage/files
    env_file:
      - stack.env
    ports:
      - 8095:8080
```

stack.env (redacted):
```
APP_ENV=dev
APP_SECRET=************
MESSENGER_TRANSPORT_DSN=doctrine://default?auto_setup=0
LOCK_DSN=flock
STRAVA_CLIENT_ID=*****
STRAVA_CLIENT_SECRET=******
STRAVA_REFRESH_TOKEN=******
UNIT_SYSTEM=metric
ACTIVITY_TYPES_TO_IMPORT='["Run"]'
ATHLETE_BIRTHDAY=1975-05-08
ATHLETE_WEIGHTS='{}'
FTP_VALUES='{}'
```

**Screenshots**
Error Message from Console:
```
In RequestException.php line 111:
                                                                                                                                           
  Client error: `GET https://www.strava.com/api/v3/athlete/activities?page=1&per_page=200` resulted in a `401 Unauthorized` response:      
  {"message":"Authorization Error","errors":[{"resource":"AccessToken","field":"activity:read_permission","code":"missing" (truncated...)  
                                                                                                                                           
app:strava:import-data
```
